"""game URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from mysite.views import *
from mysite import views


import mysite.views

urlpatterns = [
    #url for login

    url(r'^$', homePage),
    url(r'^startGame/', startGame, name="startGame"),
    url(r'^admin/', admin.site.urls),
    url(r'^selectCharactor/', views.selectCharactor, name="selectCharactor"),
    url(r'^gameIntroduction/', views.gameIntroduction, name="gameIntroduction"),
    url(r'^teamIntroduction/', views.teamIntroduction, name="teamIntroduction"),
    url(r'^settings1/', views.settings1, name="settings1"),
    url(r'^settings2/', views.settings2, name="settings2"),
    url(r'^settings3/', views.settings3, name="settings3"),
    url(r'^settings4/', views.settings4, name="settings4"),

    #url for emico in first and second grade

    url(r'^start/', views.start, name="start"),
    url(r'^eatop/', views.eatop, name="eatop"),
    url(r'^eatgood/', views.eatgood, name="eatgood"),
    url(r'^eatgood2/', views.eatgood2, name="eatgood2"),
    url(r'^eatgood3/', views.eatgood3, name="eatgood3"),
    url(r'^eatno/', views.eatno, name="eatno"),
    url(r'^class1/', views.class1, name="class1"),
    url(r'^classop/', views.classop, name="classop"),
    url(r'^classbook/', views.classbook, name="classbook"),
    url(r'^classvideo/', views.classvideo, name="classvideo"),
    url(r'^classsleep/', views.classsleep, name="classsleep"),
    url(r'^home/', views.home, name="home"),
    url(r'^homeop/', views.homeop, name="homeop"),
    url(r'^homeop101/', views.homeop101, name="homeop101"),
    url(r'^eatgood4/', views.eatgood4, name="eatgood4"),
    url(r'^eatgood5/', views.eatgood5, name="eatgood5"),
    url(r'^eatgood6/', views.eatgood6, name="eatgood6"),
    url(r'^eatgood7/', views.eatgood7, name="eatgood7"),
    url(r'^eatop2/', views.eatop2, name="eatop2"),
    url(r'^homeop103/', views.homeop103, name="homeop103"),
    url(r'^homeop104/', views.homeop104, name="homeop104"),
    url(r'^club/', views.club, name="club"),
    url(r'^club1/', views.club1, name="club1"),
    url(r'^club2/', views.club2, name="club2"),
    url(r'^club3/', views.club3, name="club3"),
    url(r'^lover/', views.lover, name="lover"),
    url(r'^loverop/', views.loverop, name="loverop"),
    url(r'^loverlove/', views.loverlove, name="loverlove"),
    url(r'^loverlove2/', views.loverlove2, name="loverlove2"),
    url(r'^loverlove3/', views.loverlove3, name="loverlove3"),
    url(r'^lovertalk/', views.lovertalk, name="lovertalk"),
    url(r'^camp/', views.camp, name="camp"),
    url(r'^campgo/', views.campgo, name="campgo"),
    url(r'^midterm/', views.midterm, name="midterm"),
    url(r'^midtermop/', views.midtermop, name="midtermop"),
    url(r'^prom/', views.prom, name="prom"),
    url(r'^promgo/', views.promgo, name="promgo"),
    url(r'^final/', views.final, name="final"),
    url(r'^winterVacation1/', views.winterVacation1, name="winterVacation1"),
    url(r'^winterVacation101/', views.winterVacation101, name="winterVacation101"),
    url(r'^winterVacation102/', views.winterVacation102, name="winterVacation102"),
    url(r'^winterVacationEnd1/', views.winterVacationEnd1, name="winterVacationEnd1"),
    url(r'^ktv/', views.ktv, name="ktv"),
    url(r'^ktvgo/', views.ktvgo, name="ktvgo"),
    url(r'^secondDrop1/', views.secondDrop1, name="secondDrop1"),
    url(r'^secondDrop1ok/', views.secondDrop1ok, name="secondDrop1ok"),
    url(r'^summerVacation1/', views.summerVacation1, name="summerVacation1"),
    url(r'^summerVacation101/', views.summerVacation101, name="summerVacation101"),
    url(r'^summerVacation102/', views.summerVacation102, name="summerVacation102"),
    url(r'^summerVacation103/', views.summerVacation103, name="summerVacation103"),
    url(r'^summerVacation104/', views.summerVacation104, name="summerVacation104"),
    url(r'^rentHouse/', views.rentHouse, name="rentHouse"),
    url(r'^sophomoreOp/', views.sophomoreOp, name="sophomoreOp"),
    url(r'^sophomoreOp101/', views.sophomoreOp101, name="sophomoreOp101"),
    url(r'^sophomoreOp102/', views.sophomoreOp102, name="sophomoreOp102"),
    url(r'^sophomoreOp103/', views.sophomoreOp103, name="sophomoreOp103"),
    url(r'^sophomoreOp104/', views.sophomoreOp104, name="sophomoreOp104"),
    url(r'^lover2/', views.lover2, name="lover2"),
    url(r'^loverop2/', views.loverop2, name="loverop2"),
    url(r'^loverok/', views.loverok, name="loverok"),
    url(r'^loverEnd/', views.loverEnd, name="loverEnd"),
    url(r'^secondDrop2/', views.secondDrop2, name="secondDrop2"),
    url(r'^secondDrop2ok/', views.secondDrop2ok, name="secondDrop2ok"),
    url(r'^winterVacation2/', views.winterVacation2, name="winterVacation2"),
    url(r'^winterVacation201/', views.winterVacation201, name="winterVacation201"),
    url(r'^winterVacation202/', views.winterVacation202, name="winterVacation202"),
    url(r'^sophomore2/', views.sophomore2, name="sophomore2"),
    url(r'^finalExam2/', views.finalExam2, name="finalExam2"),
    url(r'^summerVacation2/', views.summerVacation2, name="summerVacation2"),
    url(r'^summerVacation201/', views.summerVacation201, name="summerVacation201"),
    url(r'^summerVacation202/', views.summerVacation202, name="summerVacation202"),
    url(r'^summerVacation203/', views.summerVacation203, name="summerVacation203"),
    url(r'^summerVacation204/', views.summerVacation204, name="summerVacation204"),

    #url for emico in third and forth grade

    url(r'^rdGrade/', views.rdGrade, name="rdGrade"),
    url(r'^rdGradeOp/', views.rdGradeOp, name="rdGradeOp"),
    url(r'^exchangeOp/', views.exchangeOp, name="exchangeOp"),
    url(r'^countriesOp/', views.countriesOp, name="countriesOp"),
    url(r'^USA/', views.USA, name="USA"),
    url(r'^Australia/', views.Australia, name="Australia"),
    url(r'^Germany/', views.Germany, name="Germany"),
    url(r'^France/', views.France, name="France"),
    url(r'^exchangeN/', views.exchangeN, name="exchangeN"),
    url(r'^exchangeY/', views.exchangeY, name="exchangeY"),
    url(r'^volleyballCaptonOp/', views.volleyballCaptonOp, name="volleyballCaptonOp"),
    url(r'^captonY/', views.captonY, name="captonY"),
    url(r'^captonN/', views.captonN, name="captonN"),
    url(r'^summerVacation3Op/', views.summerVacation3Op, name="summerVacation3Op"),
    url(r'^summerVacation31/', views.summerVacation31, name="summerVacation31"),
    url(r'^summerVacation32/', views.summerVacation32, name="summerVacation32"),
    url(r'^summerVacation33/', views.summerVacation33, name="summerVacation33"),
    url(r'^summerVacation34/', views.summerVacation34, name="summerVacation34"),
    url(r'^senior/', views.senior, name="senior"),
    url(r'^seniorOp/', views.seniorOp, name="seniorOp"),
    url(r'^internshipOp/', views.internshipOp, name="internshipOp"),
    url(r'^masterOp/', views.masterOp, name="masterOp"),
    url(r'^takeExam/', views.takeExam, name="takeExam"),
    url(r'^work/', views.work, name="work"),
    url(r'^finalExamOp/', views.finalExamOp, name="finalExamOp"),
    url(r'^graduation/', views.graduation, name="graduation"),
    url(r'^finishGame/', views.finishGame, name="finishGame"),
    url(r'^gameOver/', views.gameOver, name="gameOver"),

    




    #url for karen in first and second grade

    url(r'^startk/', views.startk, name="startk"),
    url(r'^eatopk/', views.eatopk, name="eatopk"),
    url(r'^eatgoodk/', views.eatgoodk, name="eatgoodk"),
    url(r'^eatgood2k/', views.eatgood2k, name="eatgood2k"),
    url(r'^eatgood3k/', views.eatgood3k, name="eatgood3k"),
    url(r'^eatnok/', views.eatnok, name="eatnok"),
    url(r'^class1k/', views.class1k, name="class1k"),
    url(r'^classopk/', views.classopk, name="classopk"),
    url(r'^classbookk/', views.classbookk, name="classbookk"),
    url(r'^classvideok/', views.classvideok, name="classvideok"),
    url(r'^classsleepk/', views.classsleepk, name="classsleepk"),
    url(r'^homek/', views.homek, name="homek"),
    url(r'^homeopk/', views.homeopk, name="homeopk"),
    url(r'^homeop101k/', views.homeop101k, name="homeop101k"),
    url(r'^eatgood4k/', views.eatgood4k, name="eatgood4k"),
    url(r'^eatgood5k/', views.eatgood5k, name="eatgood5k"),
    url(r'^eatgood6k/', views.eatgood6k, name="eatgood6k"),
    url(r'^eatgood7k/', views.eatgood7k, name="eatgood7k"),
    url(r'^eatop2k/', views.eatop2k, name="eatop2k"),
    url(r'^homeop103k/', views.homeop103k, name="homeop103k"),
    url(r'^homeop104k/', views.homeop104k, name="homeop104k"),
    url(r'^clubk/', views.clubk, name="clubk"),
    url(r'^club1k/', views.club1k, name="club1k"),
    url(r'^club2k/', views.club2k, name="club2k"),
    url(r'^club3k/', views.club3k, name="club3k"),
    url(r'^loverk/', views.loverk, name="loverk"),
    url(r'^loveropk/', views.loveropk, name="loveropk"),
    url(r'^loverlovek/', views.loverlovek, name="loverlovek"),
    url(r'^loverlove2k/', views.loverlove2k, name="loverlove2k"),
    url(r'^loverlove3k/', views.loverlove3k, name="loverlove3k"),
    url(r'^lovertalkk/', views.lovertalkk, name="lovertalkk"),
    url(r'^campk/', views.campk, name="campk"),
    url(r'^campgok/', views.campgok, name="campgok"),
    url(r'^midtermk/', views.midtermk, name="midtermk"),
    url(r'^midtermopk/', views.midtermopk, name="midtermopk"),
    url(r'^promk/', views.promk, name="promk"),
    url(r'^promgok/', views.promgok, name="promgok"),
    url(r'^finalk/', views.finalk, name="finalk"),
    url(r'^winterVacation1k/', views.winterVacation1k, name="winterVacation1k"),
    url(r'^winterVacation101k/', views.winterVacation101k, name="winterVacation101k"),
    url(r'^winterVacation102k/', views.winterVacation102k, name="winterVacation102k"),
    url(r'^winterVacationEnd1k/', views.winterVacationEnd1k, name="winterVacationEnd1k"),
    url(r'^ktvk/', views.ktvk, name="ktvk"),
    url(r'^ktvgok/', views.ktvgok, name="ktvgok"),
    url(r'^secondDrop1k/', views.secondDrop1k, name="secondDrop1k"),
    url(r'^secondDrop1okk/', views.secondDrop1okk, name="secondDrop1okk"),
    url(r'^summerVacation1k/', views.summerVacation1k, name="summerVacation1k"),
    url(r'^summerVacation101k/', views.summerVacation101k, name="summerVacation101k"),
    url(r'^summerVacation102k/', views.summerVacation102k, name="summerVacation102k"),
    url(r'^summerVacation103k/', views.summerVacation103k, name="summerVacation103k"),
    url(r'^summerVacation104k/', views.summerVacation104k, name="summerVacation104k"),
    url(r'^rentHousek/', views.rentHousek, name="rentHousek"),
    url(r'^sophomoreOpk/', views.sophomoreOpk, name="sophomoreOpk"),
    url(r'^sophomoreOp101k/', views.sophomoreOp101k, name="sophomoreOp101k"),
    url(r'^sophomoreOp102k/', views.sophomoreOp102k, name="sophomoreOp102k"),
    url(r'^sophomoreOp103k/', views.sophomoreOp103k, name="sophomoreOp103k"),
    url(r'^sophomoreOp104k/', views.sophomoreOp104k, name="sophomoreOp104k"),
    url(r'^lover2k/', views.lover2k, name="lover2k"),
    url(r'^loverop2k/', views.loverop2k, name="loverop2k"),
    url(r'^loverokk/', views.loverokk, name="loverokk"),
    url(r'^loverEndk/', views.loverEndk, name="loverEndk"),
    url(r'^secondDrop2k/', views.secondDrop2k, name="secondDrop2k"),
    url(r'^secondDrop2okk/', views.secondDrop2okk, name="secondDrop2okk"),
    url(r'^winterVacation2k/', views.winterVacation2k, name="winterVacation2k"),
    url(r'^winterVacation201k/', views.winterVacation201k, name="winterVacation201k"),
    url(r'^winterVacation202k/', views.winterVacation202k, name="winterVacation202k"),
    url(r'^sophomore2k/', views.sophomore2k, name="sophomore2k"),
    url(r'^finalExam2k/', views.finalExam2k, name="finalExam2k"),
    url(r'^summerVacation2k/', views.summerVacation2k, name="summerVacation2k"),
    url(r'^summerVacation201k/', views.summerVacation201k, name="summerVacation201k"),
    url(r'^summerVacation202k/', views.summerVacation202k, name="summerVacation202k"),
    url(r'^summerVacation203k/', views.summerVacation203k, name="summerVacation203k"),
    url(r'^summerVacation204k/', views.summerVacation204k, name="summerVacation204k"),

    #url for emico in third and forth grade

    url(r'^rdGradek/', views.rdGradek, name="rdGradek"),
    url(r'^rdGradeOpk/', views.rdGradeOpk, name="rdGradeOpk"),
    url(r'^exchangeOpk/', views.exchangeOpk, name="exchangeOpk"),
    url(r'^countriesOpk/', views.countriesOpk, name="countriesOpk"),
    url(r'^USAk/', views.USAk, name="USAk"),
    url(r'^Australiak/', views.Australiak, name="Australiak"),
    url(r'^Germanyk/', views.Germanyk, name="Germanyk"),
    url(r'^Francek/', views.Francek, name="Francek"),
    url(r'^exchangeNk/', views.exchangeNk, name="exchangeNk"),
    url(r'^exchangeYk/', views.exchangeYk, name="exchangeYk"),
    url(r'^volleyballCaptonOpk/', views.volleyballCaptonOpk, name="volleyballCaptonOpk"),
    url(r'^captonYk/', views.captonYk, name="captonYk"),
    url(r'^captonNk/', views.captonNk, name="captonNk"),
    url(r'^summerVacation3Opk/', views.summerVacation3Opk, name="summerVacation3Opk"),
    url(r'^summerVacation31k/', views.summerVacation31k, name="summerVacation31k"),
    url(r'^summerVacation32k/', views.summerVacation32k, name="summerVacation32k"),
    url(r'^summerVacation33k/', views.summerVacation33k, name="summerVacation33k"),
    url(r'^summerVacation34k/', views.summerVacation34k, name="summerVacation34k"),
    url(r'^seniork/', views.seniork, name="seniork"),
    url(r'^seniorOpk/', views.seniorOpk, name="seniorOpk"),
    url(r'^internshipOpk/', views.internshipOpk, name="internshipOpk"),
    url(r'^masterOpk/', views.masterOpk, name="masterOpk"),
    url(r'^takeExamk/', views.takeExamk, name="takeExamk"),
    url(r'^workk/', views.workk, name="workk"),
    url(r'^finalExamOpk/', views.finalExamOpk, name="finalExamOpk"),
    url(r'^graduationk/', views.graduationk, name="graduationk"),
    url(r'^finishGamek/', views.finishGamek, name="finishGamek"),




    #

    url(r'^startt/', views.startt, name="startt"),
]
