# Generated by Django 2.2 on 2019-05-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='friendship',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='health',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wealth',
            field=models.IntegerField(default=0),
        ),
    ]
